version: '3.1'

services:
  orchestrator-graphql:
    build: ./server/orchestrator-graphql
    environment:
      REDIS_PW: ${REDIS_PW}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - '80:4000'

  service-item:
    build: ./server/service-items
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '4001:4001'

  service-user:
    build: ./server/service-users
    environment:
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - '4002:4002'
